In [1]:
import numpy as np

In [2]:
#Sci-fy Library and Matplotlib Library

In [3]:
arr = np.array([1,2,3],dtype="int")

In [4]:
arr

array([1, 2, 3])

In [5]:
#Some Methods

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr1 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [8]:
arr1.shape

(2, 7)

In [9]:
#get dimension
arr1.ndim

2

In [10]:
arr1.size

14

In [11]:
arr1.itemsize

4

In [12]:
str(arr1.__dir__())

"['__repr__', '__str__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__iter__', '__add__', '__radd__', '__sub__', '__rsub__', '__mul__', '__rmul__', '__mod__', '__rmod__', '__divmod__', '__rdivmod__', '__pow__', '__rpow__', '__neg__', '__pos__', '__abs__', '__bool__', '__invert__', '__lshift__', '__rlshift__', '__rshift__', '__rrshift__', '__and__', '__rand__', '__xor__', '__rxor__', '__or__', '__ror__', '__int__', '__float__', '__iadd__', '__isub__', '__imul__', '__imod__', '__ipow__', '__ilshift__', '__irshift__', '__iand__', '__ixor__', '__ior__', '__floordiv__', '__rfloordiv__', '__truediv__', '__rtruediv__', '__ifloordiv__', '__itruediv__', '__index__', '__matmul__', '__rmatmul__', '__imatmul__', '__len__', '__getitem__', '__setitem__', '__delitem__', '__contains__', '__new__', '__array__', '__array_prepare__', '__array_wrap__', '__array_ufunc__', '__array_function__', '__sizeof__', '__copy__', '__deepcopy__', '__reduce__', '__reduce_ex__', '__setstate__', 'dumps'

In [13]:
arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [14]:
arr1[0,3] = 4

In [15]:
arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
# !pip install --upgrade jupyterthemes

In [20]:
arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [26]:
#Get More Examples 

#1. Slicing
#2. Indexing
#3. Change Values using indexing

In [33]:
arr1[:,1:-1:2] #Slicing(Startindex:Endindex:Increment)

array([[ 2,  4,  6],
       [ 9, 11, 13]])

In [36]:
arr1[0,1] = 1

In [39]:
arr1

array([[ 1,  1,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [86]:
#Get More Methods

#1. Zeros
#2. Ones
#3. Full
#4. Full_like
#5. random.rand its takes 2 params row and columns
#6. random.random_sample it takes a tuple as an parameter so you can pass a shape of any array
#7. for getting random integer values use randint (number:you will get number that is lesser than you specified,and pass size=(3,3))
#8 identity for diagonal matrix

#1 Zeros

In [59]:
np.zeros((2,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
np.zeros(2,dtype="int")

array([0, 0])

In [68]:
arr2 = np.array(range(1,10))

In [71]:
arr2 = arr2.reshape(3,3)

In [74]:
np.zeros_like(arr2,dtype="float") #you can change the datatype

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#2 Ones

In [79]:
np.ones((2,3),dtype="float")

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.ones(2)

array([1., 1.])

In [84]:
arr3 = np.random.randint(7,size=(3,3))

In [85]:
arr3

array([[5, 0, 2],
       [1, 4, 1],
       [4, 2, 0]])

In [88]:
np.ones_like(arr3,dtype="float")

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [90]:
np.ones((2,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1]])

#3 Full

In [98]:
#full takes 2 params to create nd.array (shape,fill_value) and bydefault datatype will be integer

In [99]:
np.full((2,3),5,dtype="float")

array([[5., 5., 5.],
       [5., 5., 5.]])

#4 Full_like

In [109]:
np.full_like(np.arange(1,7).reshape(2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

#5 random.rand

In [110]:
np.random.rand(2,3)

array([[0.95103627, 0.07026942, 0.56916766],
       [0.74468357, 0.06020871, 0.45483586]])

#6 random.random_sample

In [121]:
np.random.random_sample((2,3,4,2))
# 2 arrays 1 array contains 3 nd.array 4rows and 2 cols 

array([[[[0.22979911, 0.58836211],
         [0.24128628, 0.27300059],
         [0.66173565, 0.47218756],
         [0.76042412, 0.2056913 ]],

        [[0.03796378, 0.92051463],
         [0.79877002, 0.87130583],
         [0.41232594, 0.80230091],
         [0.89481268, 0.74144524]],

        [[0.263588  , 0.37869162],
         [0.59177759, 0.81214253],
         [0.1535954 , 0.45749504],
         [0.1892239 , 0.54719101]]],


       [[[0.3411626 , 0.12819635],
         [0.30798797, 0.57652726],
         [0.78425558, 0.92832623],
         [0.3261702 , 0.95060893]],

        [[0.43847736, 0.44914721],
         [0.63897292, 0.30655106],
         [0.58656126, 0.50449682],
         [0.09540313, 0.26546834]],

        [[0.12072362, 0.67069345],
         [0.48215005, 0.7834786 ],
         [0.67148583, 0.63158601],
         [0.33664548, 0.84950638]]]])

#7 randint

In [122]:
np.random.randint(10,size=(3,3))

array([[7, 4, 6],
       [5, 9, 4],
       [2, 2, 9]])

In [126]:
np.random.randint(1,10,size=(3,3))
#you can use negative integers

array([[2, 5, 2],
       [5, 1, 5],
       [2, 6, 3]])

#8 identity

In [132]:
np.identity(5,dtype="int")
#bydefault the datatype will be float

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [133]:
#repeat method in nd.array

In [140]:
arr4 = np.array([[1,2,3]])

In [141]:
arr4

array([[1, 2, 3]])

In [145]:
np.repeat(arr4,5,axis=0) #0 for rows 1 for cols

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#Question:1
# [[1, 1, 1, 1, 1],
#  [1, 0, 0, 0, 1],
#  [1, 0, 9, 0, 1],
#  [1, 0, 0, 0, 1],
#  [1, 1, 1, 1, 1]]

In [165]:
takeones = np.ones((5,5),dtype="int")

In [166]:
takeones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [167]:
takezeros = np.zeros((3,3),dtype="int")

In [168]:
takezeros[1,1] = 9

In [169]:
takezeros

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [170]:
takeones[1:4,1:4] = takezeros

In [172]:
takeones

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])